Repository openMetadataInitiative/openMINDS_SANDS, pull requests merged in 2020-09, with the labels that each got.

#42 Update anatomicalEntity.schema.json
  v0.1/core/anatomicalEntity.schema.json
Labels: revision

#45 Electrode schemas
  v0.1/definitions.json
  v0.1/elements/electrode.schema.json
  v0.1/elements/electrodeArray.schema.json
  v0.1/elements/electrodeContact.schema.json
Labels: enhancement

#47 removed/replaced all to SANDS-internal GitHub, updated relatedOntolo…
  v0.1/core/annotationToEntity.schema.json
  v0.1/core/brainAtlas.schema.json
  v0.1/core/coordinateSpace.schema.json
  v0.1/core/entityToEntity.schema.json
  v0.1/core/terminology.schema.json
  v0.1/elements/coordinates.schema.json
  v0.1/elements/image.schema.json
  v0.1/options/axes.schema.json
  v0.1/options/indexingparameters.schema.json
Labels: bug

#50 Revision ofannotation
  v0.1/core/annotation.schema.json
  v0.1/core/visualizationParameters.schema.json
  v0.1/definitions.json
  v0.1/elements/annotationFile.schema.json
Labels: revision

#51 Revision of brain atlas
  v0.1/core/brainAtlas.schema.json
  v0.1/core/brainAtlasVersion.schema.json
  v0.1/definitions.json
Labels: revision

#52 revision of coordinateSpace according to #40
  v0.1/core/coordinateSpace.schema.json
Labels: revision
